name: between_lines
description: "A new Flutter project."

# Prevents accidental publication to pub.dev
publish_to: 'none'

# Versioning for the app
version: 1.0.0+1

# Flutter SDK version requirement
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.0
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  http: ^0.13.6
  url_launcher: ^6.2.5
  html: ^0.15.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Assets configuration (Images, Icons, and other files)
  assets:
    - assets/featured_book.jpg


