// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9fWts3CwJHWQ9u9nUhKM1-CnFVPEKseA',
    appId: '1:166322395001:web:eda54c155466de558a81a8',
    messagingSenderId: '166322395001',
    projectId: 'betweenlines-abf6d',
    authDomain: 'betweenlines-abf6d.firebaseapp.com',
    storageBucket: 'betweenlines-abf6d.firebasestorage.app',
    measurementId: 'G-DRCHTJ1LN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtbth_ts8Wsel8KKIIl6TrQW3VJVsFHZw',
    appId: '1:166322395001:android:65501147c05455be8a81a8',
    messagingSenderId: '166322395001',
    projectId: 'betweenlines-abf6d',
    storageBucket: 'betweenlines-abf6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOGMhe6TR2ohJ5aD1NX85WdN1F9Q2gLY',
    appId: '1:166322395001:ios:9da5b017a72a8af88a81a8',
    messagingSenderId: '166322395001',
    projectId: 'betweenlines-abf6d',
    storageBucket: 'betweenlines-abf6d.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOGMhe6TR2ohJ5aD1NX85WdN1F9Q2gLY',
    appId: '1:166322395001:ios:9da5b017a72a8af88a81a8',
    messagingSenderId: '166322395001',
    projectId: 'betweenlines-abf6d',
    storageBucket: 'betweenlines-abf6d.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9fWts3CwJHWQ9u9nUhKM1-CnFVPEKseA',
    appId: '1:166322395001:web:94df152ad106c1848a81a8',
    messagingSenderId: '166322395001',
    projectId: 'betweenlines-abf6d',
    authDomain: 'betweenlines-abf6d.firebaseapp.com',
    storageBucket: 'betweenlines-abf6d.firebasestorage.app',
    measurementId: 'G-2K524N307T',
  );
}
